# Generated by Django 2.1.15 on 2020-06-15 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hate_users',
            field=models.ManyToManyField(related_name='hate_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
